export const spots = [
  {
    img: "assets/img/png/hole.png",
    posX: "2%",
    posY: "65%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "2%",
    posY: "75%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "8%",
    posY: "60%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "8%",
    posY: "70%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "16%",
    posY: "60%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "16%",
    posY: "70%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "26%",
    posY: "30%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "40%",
    posY: "20%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "45%",
    posY: "42%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "45%",
    posY: "70%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hole.png",
    posX: "65%",
    posY: "83%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "62%",
    posY: "82%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "65%",
    posY: "60%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "77%",
    posY: "58%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "77%",
    posY: "76%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "96%",
    posY: "58%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "81%",
    posY: "58%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hole.png",
    posX: "83%",
    posY: "93%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "87%",
    posY: "92%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "95%",
    posY: "78%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "90%",
    posY: "60%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "95%",
    posY: "45%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "90%",
    posY: "25%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "71%",
    posY: "12%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "60%",
    posY: "5%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "60%",
    posY: "45%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "48%",
    posY: "45%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "78%",
    posY: "45%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "45%",
    posY: "25%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "28%",
    posY: "44%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "28%",
    posY: "73%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "45%",
    posY: "61%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "1%",
    posY: "25%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "20%",
    posY: "40%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "35%",
    posY: "58%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "10%",
    posY: "25%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "48%",
    posY: "78%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "71%",
    posY: "79%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "50%",
    posY: "5%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/hideBox.png",
    posX: "48%",
    posY: "60%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "12%",
    posY: "75%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "22%",
    posY: "75%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "32%",
    posY: "75%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "38%",
    posY: "75%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "30%",
    posY: "30%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "32%",
    posY: "47%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "20%",
    posY: "27%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "1%",
    posY: "45%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "55%",
    posY: "48%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "55%",
    posY: "5%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "48%",
    posY: "15%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "48%",
    posY: "25%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "77.5%",
    posY: "25%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "84%",
    posY: "47%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "86%",
    posY: "62%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "95%",
    posY: "28%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "62%",
    posY: "65%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "81%",
    posY: "81%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "74%",
    posY: "63%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "67%",
    posY: "13%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "55%",
    posY: "82%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "65%",
    posY: "75%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/vent.png",
    posX: "96%",
    posY: "71%",
    isImposter: false,
    wasClicked: false,
  },
  {
    img: "assets/img/png/trash.png",
    posX: "84%",
    posY: "25%",
    isImposter: false,
    wasClicked: false,
  },
];
