export const spots = [
  { img: "assets/img/png/hole.png", posX: "5%", posY: "5%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/vent.png", posX: "10%", posY: "10%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/hideBox.png", posX: "15%", posY: "15%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "20%", posY: "20%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "25%", posY: "25%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "30%", posY: "30%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "35%", posY: "35%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "40%", posY: "40%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "45%", posY: "45%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "50%", posY: "50%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/hole.png", posX: "55%", posY: "55%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/vent.png", posX: "60%", posY: "60%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/hideBox.png", posX: "65%", posY: "65%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "70%", posY: "70%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "75%", posY: "75%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "80%", posY: "80%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/trash.png", posX: "85%", posY: "85%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/hole.png", posX: "90%", posY: "90%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/vent.png", posX: "95%", posY: "95%", isImposter: false, wasClicked: false },
  { img: "assets/img/png/hideBox.png", posX: "100%", posY: "100%", isImposter: false, wasClicked: false },
];
